# mockbin-setup.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: mockbin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockbin-deployment
  namespace: mockbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockbin
  template:
    metadata:
      labels:
        app: mockbin
    spec:
      containers:
      - name: mockbin
        image: mockbin/mockbin
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mockbin-service
  namespace: mockbin
spec:
  selector:
    app: mockbin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
